version: "3"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/migrations/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  # model:
  #   context: ./model
  #   env_file:
  #     - ./model/.env
  #   ports:
  #     - "8080:8080"

volumes:
  postgres_data:
