version: "3"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/migrations/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  model:
    image: ${MODEL_IMAGE:-property_pricing-base_model:1.0}
    ports:
      - "8081:8081"

  app:
    image: ${APP_IMAGE:-property_pricing-app:latest}
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING:-postgresql://postgres:postgres@postgres:5432/property_db}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
