name: Build Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

      MODEL_NAME: base_model
      MODEL_VERSION: 1.0
      FEAST_REPO_DIR: ./feature_repo_dev
      ARTIFACTS_DIR: ./artifacts/base_model_1.0
      CONFIG_PATH: ./cfgs/base_model.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker tag property_pricing/$MODEL_NAME:$MODEL_VERSION $ECR_REPOSITORY/$MODEL_NAME:$MODEL_VERSION
          docker tag property_pricing/app:latest $ECR_REPOSITORY/app:latest
          docker push $ECR_REPOSITORY/$MODEL_NAME:$MODEL_VERSION
          docker push $ECR_REPOSITORY/app:latest
